FROM mariadb:latest

ENV MARIADB_ROOT_PASSWORD=root
ENV MARIADB_DATABASE=saedb
ENV MARIADB_USER=saeuser
ENV MARIADB_PASSWORD=lannion

COPY ./Save_bdd/bdd.sql /docker-entrypoint-initdb.d/
COPY ./Save_bdd/comptes.sql /docker-entrypoint-initdb.d/

EXPOSE 3306